### ISSUE TITLE
Adapt MATLAB log for species-specific GECKO scripts

### ISSUE THREAD

**Issue by IVANDOMENZAIN** [MetabolicAtlas/ecModels#72]
The [PR#128](https://github.com/SysBioChalmers/GECKO/pull/128/files) in GECKO has modified the MATLAB log for the whole GECKO pipeline. Most of this functions are species-agnostic and will run directly from GECKO without any introduced change by the scripts in the ecModels container pipeline. However some of the species-specific functions are also part of this PR in GECKO, which means that they're gonna be substituted by the scripts in this repo everytime the pipeline is run, which may create heterogeneity in the resulting logs for each species. The solution is to go species by species and change the following functions according to the changes in aforemention PR in GECKO:

- [ ] preprocessModel.m
- [ ] manualModifications.m

These changes should be introduced in the base branch of this repository (feat/updated-models).

**Comment by mihai-sysbio** [comment]
Should we try out the GECKO branch `style/log` in `config.ini`?

**Comment by IVANDOMENZAIN** [comment]
@mihai-sysbio sounds good to me. In which branch in this fork repo are you thinking for testing this?

**Comment by IVANDOMENZAIN** [comment]
> @mihai-sysbio sounds good to me. In which branch in this fork repo are you thinking for testing this
It doesn't matter, #73 has been merged now :)
